### PR TITLE
feat!: custom validation logic, call for code, fixes

### LINKED ISSUE #21: Mixed uncontrolled inputs in phone OTP input
Get rid of this error,

### PR DESCRIPTION
**Pull request by paolodamico**
- Renamed `onSuccess` callback to `onVerification`
- Dev can now return a promise on the `onVerification` method to run any custom logic on their end to verify any of the signals. The app will show a loading state while this is happening.
    
    - If the promise is rejected, an error state will be shown instead.
- Connects retry mechanism.
- Allows user to request code via phone call instead.
- Updates copy on the "About" section
- Fixes #21

### CODE REVIEW

File: example-react/src/App.tsx [hunk 1]
```diff
@@ -3,14 +3,24 @@ import { IDKitWidget, ISuccessResult } from "@worldcoin/idkit";
...
 	};
 
 	return (
 		<div
 			className="App"
 			style={{ minHeight: "100vh", display: "flex", justifyContent: "center", alignItems: "center" }}
 		>
-			<IDKitWidget actionId="get_this_from_the_dev_portal" onSuccess={handleProof}>
+			<IDKitWidget
+				actionId="wid_staging_f56691ad61aaf0021ab317e29cf11820"
```
Comment (maxpetretta) [inline example-react/src/App.tsx:20]: Left the staging action in the commit

File: idkit/src/index.html [hunk 2]
```diff
@@ -41,16 +41,18 @@ <h1 id="heading">idkit-js</h1>
 		<script>
 			IDKit.init({
 				signal: 'test_signal',
-				actionId: 'wid_staging_1234',
+				actionId: 'wid_staging_f56691ad61aaf0021ab317e29cf11820',
```
Comment (maxpetretta) [inline idkit/src/index.html:44]: Left the staging action in the commit

**Review by maxpetretta — CHANGES_REQUESTED** [review]

**Review by maxpetretta — APPROVED** [review]
